- bin/find_dead_links
```
$ ./bin/find_dead_links
Found 342 unique links
Dead link: https://www.hypernode.nl/domeinnaam/
Couldn't get http://www: HTTPConnectionPool(host='www', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f37c24dc070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Dead link: https://www.byte.nl/blog/afbeeldingen-optimaliseren-magento-bespaart-veel-webruimte/
Couldn't get https://archive.support.hypernode.com/knowledgebase/use-nodejs-npm-hypernode/#Using_a_newer_version_of_NodeJs: HTTPSConnectionPool(host='archive.support.hypernode.com', port=443): Max retries exceeded with url: /knowledgebase/use-nodejs-npm-hypernode/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection …
```
> Script to find dead links

- docs/conf.py
- requirements/base.txt
To write mermaid diagrams, see: https://github.com/mgaitan/sphinxcontrib-mermaid.
```markdown
```{mermaid}
sequenceDiagram
participant Alice
participant Bob
Alice->John: Hello John, how are you?
loop Healthcheck
John->John: Fight against hypochondria
end
Note right of John: Rational thoughts <br/>prevail...
John-->Alice: Great!
John->Bob: How about you?
Bob-->John: Jolly good!
```
> extensions: Add sphinxcontrib-mermaid

- docs/troubleshooting/performance/how-to-identify-and-stop-long-running-processes.md
- Fixed typo in meta title
- Added redirect_from path
- Corrected syntax highlighting for code blocks
> docs: Update how-to-identify-and-stop-long-running-processes.md

- docs/hypernode-platform/varnish/how-to-enable-varnish-on-hypernode.md
> add missing space how to enable varnish docs

- docs/ecommerce-applications/akeneo/how-to-install-akeneo-6-on-hypernode.md
Reverts ByteInternet/hypernode-docs-next#105, because the changes were revised in #108
> Revert "PHP_Version should be 8.1"

- docs/about-hypernode/support/emergency-support-outside-office-hours.md
Reverts ByteInternet/hypernode-docs-next#110
> Revert "Revert "Updated opening hours support""

- docs/services/control-panel/how-to-transfer-ownership-of-a-hypernode-in-the-control-panel.md
- Added info about Account settings page in CP
> Added how to change account settings

- docs/about-hypernode/billing/billing-faq-for-the-service-panel.md
Removed link to old article about Service Panel in order to delete the old article.
> Removed link to old article

- docs/about-hypernode/about-hypernode/what-kind-of-emails-does-hypernode-send.md
- Added manage email preference settings in the Control Panel
> Added manage preference settings in Control Panel

- docs/hypernode-platform/dns/dns-for-control-panel-users.md
- Removed Service Panel specific information
- Added how to manage DNS in the Control Panel
> Updated DNS article to Control Panel

- docs/services/domain-procedures/Which-TLDs-does-Hypernode-offer.md
- docs/services/domain-procedures/which-tlds-does-hypernode-offer.md
The page is not done yet. However, I cannot create a new page. I get an error that I do not know how to solve.
> New doc: Domain extensions

- docs/best-practices/testing/hypernode-docker.md
- Add syntax highlighting
- Fix link to changing base url for Magento 1.x/2.x
- Remove note about elasticsearch 7.x
- Format nginx example
> Update Hypernode Docker article

- docs/services/control-panel/how-to-use-teams.md
"All users can add a developer to their team. "
removed cause not true
> Sentence removed

- docs/services/domain-procedures/which-tlds-does-hypernode-offer.md
- Added text on How to transfer
- Added link to specific TLD transfer info
- Added link to CP
> Updated TLD article with extra info

- docs/hypernode-platform/ssh/how-to-log-in-to-the-hypernode-with-ssh.md
Removed Service Panel specific information from how-to-log-in-to-the-hypernode-with-ssh article
> Removed SP specific info from SSH article

- docs/hypernode-platform/tools/hypernode-brancher.md
A new feature was added to Brancher, called Brancher install hooks.
> brancher: Add documentation for the Brancher install hook

- .github/workflows/deploy.yaml
- deploy.php
- docs/conf.py
- hypernode/sphinx/extensions/github_actions_logging.py
- hypernode/sphinx/extensions/meta_robots.py
- hypernode/sphinx/extensions/updated_at.py
This will be very helpful for collaborators to find out what is causing the sphinx build to fail
> ci: Report sphinx build errors to Github Actions workflow summary

- docs/_static/css/general.css
- docs/_static/css/main.css
- docs/_static/scss/general.scss
- docs/_templates/layout.html
> adding feedback group tile to docs

- docs/services/control-panel/different-control-panel-scenarios.md
Removed specific SP info and reference
> Updated different control panel scenarios

- docs/about-hypernode/billing/waarom-facturatie-vanuit-hypernode-ipv-hipex.md
Made a Billing FAQ for the Hipex>Hypernode migration at the request of Dennis and Sylvia
> Created Hipex-Hypernode Billing FAQ

- docs/about-hypernode/billing/waarom-facturatie-vanuit-hypernode-ipv-hipex.md
> Updated billing article - missed a header

- docs/about-hypernode/billing/how-to-up-or-downgrade-your-hypernode-plan.md
Removed how to change your plan on the SP
> Removed SP specific info

- docs/about-hypernode/billing/how-to-cancel-your-plan.md
How to cancel via the SP removed
> Removed SP specific info in how to cancel

- docs/hypernode-platform/php/supported-php-versions-and-how-to-change-them-on-hypernode.md
Removed SP instructions, added PHP 8.2
> Updated Supported PHP versions

- docs/hypernode-platform/tools/installation-and-configuration-of-pm2.md
Now make use if `pm2-runtime` instead of pm2 with daemonless flag.
> Change PM2 documentation

- docs/best-practices/security/how-to-fix-malicious-javascript-credit-card-hijack.md
- docs/hypernode-platform/nginx/how-to-block-user-agents-and-referrer-sites.md
- docs/hypernode-platform/ssl/how-to-use-lets-encrypt-on-hypernode.md
- docs/hypernode-platform/tools/how-to-use-periodic-tasks-cronjobs-on-hypernode.md
- docs/troubleshooting/performance/how-to-block-bad-bots-via-the-control-panel.md
- docs/troubleshooting/performance/how-to-implement-pagespeed-booster.md
- docs/troubleshooting/performance/how-to-spot-slow-extensions-using-the-php-slow-logs.md
I'm not sure yet which dependency has updated, but I suspect it's a newer version of `ruamel.yaml` which is a dependency of `mdformat-frontmatter`. 
Anyway, the formatting looks better this way so let's apply it :).
> Apply updated documentation formatting

- docs/_static/css/general.css
- docs/_static/css/main.css
- docs/_static/scss/general.scss
- docs/_templates/layout.html
- docs/_templates/searchbox.html
Added API docs / Docs tabs next to login button and added search icon in the searchbar.
> modifying header to fit api docs header 

- docs/ecommerce-applications/magento-2/how-to-configure-varnish-for-magento-2-x.md
After we reverted [changelog 9077](https://changelog.hypernode.com/release-9077-optimized-magento-2-varnish-nginx-configuration/), I figured it'd be better to communicate this improvement in the docs instead.
> magento2/varnish: Add performance improvement section

- docs/hypernode-platform/tools/how-to-use-node-js-and-npm-on-hypernode.md
- Remove obsolete examples
- Better instructions
- Better wording
> tools/nodejs: Update documentation

- docs/about-hypernode/support/emergency-support-outside-office-hours.md
- docs/about-hypernode/support/scope-of-support.md
- docs/about-hypernode/support/what-to-expect-from-hipex-support.md
Also restructured the Hipex support page, headings weren't nested properly
> support: Update office hours in docs

- docs/hypernode-platform/tools/how-to-use-the-hypernode-systemctl-cli-tool.md
looks like:
```
app@wifbd2-test-magweb-cmbl:~$ hypernode-systemctl settings php_amqp_enabled True
app@wifbd2-test-magweb-cmbl:~$ php -i | grep amqp -i
/etc/php/7.1/cli/conf.d/20-amqp.ini,
app@gs222w-test2-magweb-cmbl:~$ hypernode-systemctl settings php_amqp_enabled False
app@gs222w-test2-magweb-cmbl:~$ php -i | grep amqp
app@gs222w-test2-magweb-cmbl:~$ 
```
> add php-amqp to docs

- docs/ecommerce-applications/magento-2/how-to-configure-varnish-for-magento-2-x.md
- docs/ecommerce-applications/shopware-5/how-to-configure-varnish-for-shopware-5.md
- docs/ecommerce-applications/shopware-6/how-to-configure-varnish-for-shopware-6.md
Add additional varnish documentation for cluster setups
> Add additional varnish documentation for cluster setups

- docs/services/control-panel/what-overloaded-server-means-and-how-to-prevent-that.md
We updated metrics to be visible for all of the customers, so I remove the note
> removing the note from docs about metrics

- docs/conf.py
- hypernode/sphinx/extensions/json_sitemap.py
The sitemap is generated at /sitemap.json if the DOCS_BASE_URL environment variable is set.
> Add json sitemap generator

- docs/services/control-panel/how-to-change-legal-owner-whois-of-the-domain-in-the-control-panel.md
- docs/services/control-panel/how-to-change-the-owner-of-a-domain-in-the-control-panel.md
- docs/services/control-panel/how-to-order-a-hypernode-for-someone-else.md
- docs/services/control-panel/how-to-transfer-ownership-of-a-hypernode-in-the-control-panel.md
- docs/services/control-panel/what-overloaded-server-means-and-how-to-prevent-that.md
Some of the titles had lowercased titles and it look weird in the list
> rename few titles to capitalized-each-word

- docs/hypernode-platform/autoscaling/how-does-autoscaling-work.md
This docs have two iteration. First two pages are from Alejandro, the rest is from Iza. Final conclusion is going with Alejandro's content. 
According to verbal request I have added some headings in the text to make it more SEO friendly and structured.
https://docs.google.com/document/d/1Weo8Rt-zZPm8CnLATsSC5axGcuyBjILd2UuL1JzJTIo/edit
> Change existing Autoscaling docs with Alejandro's version

- docs/about-hypernode/billing/billing-faq-for-the-control-panel.md
- docs/best-practices/cdn/how-to-use-cloudflare-with-hypernode.md
- docs/ecommerce-applications/magento-2/how-to-create-a-sitemap-xml-for-magento-2-x.md
> How to use cloudflare with hypernode

- docs/about-hypernode/billing/billing-faq-for-the-control-panel.md
- docs/ecommerce-applications/magento-2/how-to-create-a-sitemap-xml-for-magento-2-x.md
Updated the path of the sitemap location within magento2
> Update how to create a sitemap.xml for magento 2.x

- docs/hypernode-platform/dns/dns-for-control-panel-users.md
Changed the Byte nameservers to Hypernode nameservers.
Old:
```
nsa.byte.nl
nsb.byte.nl
nsc.byte.nl
```
New:
```
ns1.hypernode.com
ns2.hypernode.com
ns3.hypernode.com
```
>  Change old nameserver from byte to Hypernode

- docs/hypernode-platform/nginx/basic-authentication-on-hypernode-development-plans.md
We often receive requests to whitelist Adyen so they can test via URI whitelist.
> added url and IP whitelist in nginx

- docs/hypernode-platform/php/supported-php-versions-and-how-to-change-them-on-hypernode.md
> add missing whitespace in php settings page

- docs/ecommerce-applications/akeneo/how-to-install-akeneo-7-on-hypernode.md
Update cron jobs in accordance with the official documentation, as some commands were deprecated. 
https://docs.akeneo.com/7.0/install_pim/manual/installation_ce.html#cron-jobs
> Update cron jobs for Akeneo7 in accordance with the official documentation

- docs/about-hypernode/support/what-to-expect-from-hipex-support.md
Changed phone number on the docs from Hipex to Hypernode.
>  Change old Hipex phone number to Hypernode

- docs/hypernode-platform/tools/how-to-use-elasticsearch-on-hypernode.md
currently the command throws an error:
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
> Updates curl command to set 0 ES replicas

- docs/about-hypernode/billing/control-panel-billing-facturen-faq-dutch.md
- docs/about-hypernode/support/hipex-to-hypernode-migration-2024-faq-dutch.md
onboarding -> billing
billling -> billing
> fix email address in docs (billling)

- docs/hypernode-platform/php/how-to-use-alternative-php-versions.md
Reverts ByteInternet/hypernode-docs-next#282
> Revert "Update how-to-use-alternative-php-versions.md"

- docs/conf.py
Make copyright dynamic in docs
> Make copyright dynamic in docs

- docs/about-hypernode/security-policies/hypernode-security-statement.md
Update the Datacenter certifications.
> Add datacenter certifications

- docs/hypernode-platform/autoscaling/pricing-for-horizontal-autoscaling.md
> remove text about prorated pricing
