ByteInternet/hypernode-docs-next

docs/hypernode-platform/tools/installation-and-configuration-of-pm2.md

Syntax highlighting was missing, a specific Hypernode instance was being referred to and there were some typos in the meta description.

docs: Improve PM2 installation doc

---

docs/_templates/layout.html

On mobile devices, the [theme-color meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) makes the browser take on the specified theme color for certain elements (like the url bar etc).
Primary color was sourced from `docs/_static/scss/colors.scss`.

Set theme-color to Hypernode primary color

---

debian/control

to fix:
```
Running setup.py install for MarkupSafe: started
Running setup.py install for MarkupSafe: finished with status 'done'
Running setup.py install for pyyaml: started
Running setup.py install for pyyaml: finished with status 'done'
Running setup.py install for ruamel.yaml.clib: started
Running setup.py install for ruamel.yaml.clib: finished with status 'done'
Running setup.py install for inotify: started
Running setup.py install for inotify: finished with status 'done'
Successfully installed GitPython-3.1.30 Jinja2-3.1.2 MarkupSafe-2.1.2 Pygments-2.14.0 alabaster-0.7.13 attrs-22.2.0 babel-2.11.0 backcall-0.2.0 beautifulsoup4-4.11.1 black-22.10.0 certifi-2022.12.7 cfgv-3.3.1 charset-normalizer-3.0.1 click-8.1.3 decorator-5.1.1 distlib-0.3.6 docutils-0.19 execnet-1.9.0 …
```

add git to build deps for manpage

---

debian/control

to prevent:
```
"mandb: can't open the manpath configuration file /etc/manpath.config", "dpkg: error processing package hndocsnext (--configure)
```

pre-depend on the man-db package

---

.github/workflows/deploy.yaml

When merging multiple branches to master, multiple deploy workflows start, but only one deploy may happen at a time. With this, deploy_production jobs will be pending if another deploy_production job is already running.

ci: Set production deploy concurrency

---

debian/rules

to prevent this error during the pip install:
```
Building wheels for collected packages: pyyaml, inotify, MarkupSafe, ruamel.yaml.clib
Running setup.py bdist_wheel for pyyaml: started
Running setup.py bdist_wheel for pyyaml: finished with status 'error'
Complete output from command /build/hndocsnext-20230124.142001/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-88vipxf9/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-65xlmawf --python-tag cp37:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel'
```

pip install wheel in debian packaging

---

.github/workflows/deploy.yaml

The default retention for a build artifact is 90 days, that's way longer than we need.

ci: Set build artifact retention

---

docs/hypernode-platform/tools/hypernode-brancher.md

- Added example for the `--label` option
- Added example for the `--clear-services` option
- Added `clear_services` setting to Hypernode Deploy example
- Replaced some occurences of "Hypernode-deploy" with "Hypernode Deploy"
- Replaced occurences of `testalex` with `example`
- Replaced some occurences of `appname` with `example`

docs: Update Brancher documentation

---

.github/workflows/deploy.yaml
docs/_templates/layout.html
docs/conf.py
hypernode/sphinx/extensions/meta_robots.py
requirements/development.txt
tests/sphinx/extensions/test_meta_robots.py

This way we prevent accidental indexation of acceptance environments by search crawlers

ci: Only allow index, follow for production

---

docs/ecommerce-applications/magento-2/how-to-create-a-sitemap-xml-for-magento-2-x.md

The current docs: Path: /sitemaps/ but this will not work because magento2 starts /data/web/magento2.  This way, the sitemap can't be saved because the sitemap directory is made here /data/web/magento2/pub/sitemaps.
The correct Path to save the sitemap to is /pub/sitemaps/.

Update path were to set sitemap magento 2

---

docs/framework/laravel.md
docs/framework/laravel/how-to-install-laravel-on-hypernode.md
docs/index.md

Since it's a framework, I decided to not put it under `ecommerce-applications` and create a new `frameworks` directory.

docs: Add how to install laravel doc

---

docs/hypernode-platform/ftp/how-to-configure-ftp-sftp-on-hypernode.md

Add a section to explain how to manage FTP users in CP

Managing FTP users in CP

---

docs/_static/pygments.css

The prompt of a console snippet should be more distinctive for readability purposes.

docs/static: Change pygments block prompt color

---

docs/hypernode-platform/backups/hypernode-backup-policy.md

Use the updated and clarified Backup Policy which contains all the information for both Snapshot, and offsite, backups.

Update Backup Policy

---

docs/hypernode-platform/cluster.md

Aside from loadbalancer setup documentation, some obsolete parts of the page have been updated as well.

docs/cluster: Add documentation on loadbalancer setup

---

docs/ecommerce-applications/akeneo/how-to-install-akeneo-7-on-hypernode.md

This is being replaced by 2.6 instead

docs: applications/akeneo: Remove reference to OpenSearch 2.x

---

docs/hypernode-platform/autoscaling/how-does-horizontal-autoscaling-work.md
docs/hypernode-platform/autoscaling/how-to-enable-horizontal-autoscaling.md
docs/hypernode-platform/autoscaling/how-to-enable-vertical-autoscaling.md

Some typo fixing, paraphrasing, etc in the doc

Some typo fixing, paraphrasing, etc in the doc

---

docs/best-practices/database/how-to-run-rabbitmq-on-hypernode.md
docs/hypernode-platform/autoscaling/how-does-horizontal-autoscaling-work.md

Split checks into hypernode and application specific

Split checks into hypernode and application specific

---

docs/_static/scss/components/_layout.scss
docs/_static/scss/components/_module.scss
docs/_static/scss/components/defaults/_code.scss
docs/_templates/layout.html

- Revert to old page layout styling
- Keep the seperated styling through scss to improve readability

Revert to old page layout styling

---

docs/hypernode-platform/autoscaling/how-does-horizontal-autoscaling-work.md

Add podman and supervisor to hypernode specific requirements doc

Add podman and supervisor to hypernode specific requirements doc

---

docs/ecommerce-applications/magento-2/how-to-configure-redis-for-magento-2.md

Fixed typo in how-to-configure-redis-for-magento-2.md

---

docs/hypernode-platform/nginx/how-to-resolve-rate-limited-requests-429-too-many-requests.md

The `conn_limit_map` variable doesn't seem to work very reliable. In our testing, we found that `limit_conn_per_ip` is much better.

docs/nginx: Update 429 resolution documentation

---

bin/watch
docs/best-practices/database/how-to-run-rabbitmq-on-hypernode.md
docs/ecommerce-applications/magento-2/how-to-configure-remote-storage-for-magento-2-x.md
docs/hypernode-platform/autoscaling/how-does-horizontal-autoscaling-work.md
requirements/development.txt

Better clarity, minor incorrect statements fixed and more explanation.
Also added a first version for remote storage for Magento 2. There's still a lot we can add there, but this is a good start :). 
The watchdog changes were needed to get `bin/watch` working on my macbook, since inotify only works on linux.

docs: Horizontal autoscaling improvements

---

.github/workflows/test.yaml
docs/ecommerce-applications/magento-2/how-to-configure-remote-storage-for-magento-2-x.md

update magento2 s3 obj storage doc

---

docs/ecommerce-applications/magento-2/how-to-configure-remote-storage-for-magento-2-x.md
docs/hypernode-platform/nginx/hypernode-managed-vhosts.md

So that I can link to it later on in the Shopware 6.x OS documentation

move magento2 OS HMV section to hypernode-managed-vhosts.md and link to it

---

.devcontainer/devcontainer.json
docs/conf.py
requirements/base.txt

Their cdn has been down a few times causing long loadtimes, and we don't use mermaid, so it's better to remove this entirely from the project.

Remove sphinxcontrib-mermaid dependency

---

docs/hypernode-platform/object-storage/getting-started-with-object-storage.md

Add cancel cmd to obj storage docs

Add cancel cmd to obj storage docs

---

docs/hypernode-platform/object-storage/dynamic-upscaling.md

Add documentation for dynamic object storage upscaling

---

bin/build_manpage
debian/rules

The documentation name has been changed from docs to documentation recently, so has the resulting name of the manpage file.

Fix build scripts for manpages
